### ISSUE TITLE
Cannot open the 

### ISSUE THREAD

**Issue by EnrcDamn** [podcast-ai/podcast-ai-lab#12]
I'm trying to load the [Lex podcast](https://content.blubrry.com/takeituneasy/lex_ai_demis_hassabis.mp3) on the app, but as soon as I launch the research I'm getting this error:

![image](https://user-images.githubusercontent.com/95379153/178123756-43c46939-dbe2-4d31-b73e-4469b430c02d.png)

@xiao11lam  Any idea what could be wrong here?

I tried to use the [csv dataframe](https://github.com/podcast-ai/podcast-ai-lab/blob/main/data/transcripts/wav2vec/20220701%20lex_ai_demis_hassabis.csv) at the moment for reading the text.

**Comment by xiao11lam** [comment]
Hey, there!
I suppose there has some issues with the the csv data format in there, you want to render the mp3 file or something?

**Comment by clstaudt** [comment]
Closing this since the code has changed significantly since then
