### ISSUE TITLE
 No such file or directory: 'data/knowledge_base/transcript_data.parquet'

### ISSUE THREAD

**Issue by xiao11lam** [podcast-ai/podcast-ai-lab#17]
![image](https://user-images.githubusercontent.com/58770171/178204992-0e410c95-c157-46f2-8502-77553e1a5e82.png)
@azuur Hey, there!
I think I do not have this .parguet file there, could you share that on the Github as well, very thankfully!

**Comment by clstaudt** [comment]
@xiao11lam  You need to run the ETL worker to create this file.

> python engine/worker.py

**Comment by xiao11lam** [comment]
Thank you, very much, Christian
I did it, yeah! I already can run the demo and see the downloading batch window, thank you for your answer.
