### ISSUE TITLE
requirements.txt malformed?

### ISSUE THREAD

**Issue by clstaudt** [podcast-ai/podcast-ai-lab#2]
@xiao11lam  I do not recognize the format of your requirements.txt file. Trying to install it with pip gives me:

```
╰─ pip install -r requirements.txt                                                                                    (podcastai) 
Processing /opt/conda/conda-bld/certifi_1655968806487/work/certifi
ERROR: Could not install packages due to an OSError: [Errno 2] No such file or directory: '/opt/conda/conda-bld/certifi_1655968806487/work/certifi'
```

**Comment by xiao11lam** [comment]
Hey, there
Already updated in the readme file there, I think you need the conda env installed there. Pls refer to the latest readme file there. You may need to activiate the conda env.
